<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use App\Events\ImportErrorOccurred;
use App\Models\Import;
use App\Models\User;

class TestImportErrorNotification extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'test:import-error-notification 
                            {--user-id=1 : User ID to send notification to}
                            {--import-id=1 : Import ID to use for testing}';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Test import error notification email system';

    /**
     * Execute the console command.
     */
    public function handle()
    {
        $userId = $this->option('user-id');
        $importId = $this->option('import-id');

        $this->info("Testing import error notification...");
        $this->line("");

        // Check if user exists
        $user = User::find($userId);
        if (!$user) {
            $this->error("User with ID {$userId} not found!");
            return 1;
        }

        $this->info("User found: {$user->name} ({$user->email})");

        // Check if import exists, or create a mock one
        $import = Import::find($importId);
        if (!$import) {
            $this->warn("Import with ID {$importId} not found. Creating a mock import record...");
            
            $import = new Import();
            $import->id = $importId;
            $import->user_id = $userId;
            $import->import_type = 'test-import';
            $import->status = 'failed';
            $import->created_at = now();
            $import->updated_at = now();
        }

        $this->info("Import record: ID {$import->id}, Type: {$import->import_type}");
        $this->line("");

        // Fire the event
        $testErrorMessage = "This is a test error message generated by the test command. Import validation failed due to missing required headers: 'sku', 'product_name'. File format appears to be corrupted.";
        
        $this->info("Firing ImportErrorOccurred event...");
        event(new ImportErrorOccurred($import, $testErrorMessage, $userId));
        
        $this->line("");
        $this->info(" Event fired successfully!");
        $this->info(" Email notification should be sent to: {$user->email}");
        $this->line("");
        $this->warn("Note: Make sure your mail configuration is set up correctly in .env file:");
        $this->line("MAIL_MAILER=smtp");
        $this->line("MAIL_HOST=your-smtp-host");
        $this->line("MAIL_PORT=587");
        $this->line("MAIL_USERNAME=your-email");
        $this->line("MAIL_PASSWORD=your-password");
        $this->line("");
        $this->info("You can also check the logs for email sending status:");
        $this->line("tail -f storage/logs/laravel.log");

        return 0;
    }
}
